name: tistory # 워크플로우 이름

on:
  schedule:
    - cron: "0 0 */1 * *"
  workflow_dispatch:
    inputs:
      name:
        description: "Person to greet"
        required: true
        default: "bossm0n5t3r"
      home:
        description: "location"
        required: false
        default: "The Octoverse"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        persist-credentials: false
        fetch-depth: 0

    - name: Set Timezone to +9 (GMT+9)
      run: sudo timedatectl set-timezone Asia/Seoul

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
          python-version: '3.x'
          architecture: 'x64'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install -y fonts-unfonts-core fonts-unfonts-extra google-chrome-stable

    - name: Run Scraper with python
      run: |
        python parser.py || echo "Parser failed" && exit 1

    - name: Set date in environment variable
      run: echo "DATE=$(date +'%Y년 %m월 %d일 %H시 %M분')" >> $GITHUB_ENV

    - name: Add & Commit
      uses: EndBug/add-and-commit@v7
      with:
        message: "블로그 자동 업데이트 : ${{ env.DATE }}"
        author_name: 'GitHub-Actions-Bot'
        add: '.'
        push: false

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'main'
        github_token: ${{ secrets.GITHUB_TOKEN }}
